# Generated by Django 5.2.10 on 2026-02-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
