# Generated by Django 5.2.10 on 2026-02-13 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_portal', '0002_alter_assessment_is_active'),
        ('user_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_portal.studentattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_portal.question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_portal.option')),
            ],
        ),
    ]
